Feature/pagination
samurojasp/GreeniePanelAdmin pull request #10
Opened 2024-06-13 19:57 UTC by luisvpan

2024-06-14 00:18 UTC, samurojasp approved these changes

2024-06-14 15:45 UTC, GreenieWarren commented
El paginador en departamentos funciona brutal, pero en criterios está raro. Una vez tengas 10 criterios y colocas otro, no aparece.

![image](https://github.com/samurojasp/GreeniePanelAdmin/assets/87400557/c4f3af4f-7774-40d8-a742-b284cd51b926)
![image](https://github.com/samurojasp/GreeniePanelAdmin/assets/87400557/f6d4853e-0de6-451c-83b8-6998353e07d4)
![image](https://github.com/samurojasp/GreeniePanelAdmin/assets/87400557/a53bd7a9-1289-4e42-9b23-4d4e4d2d98e4)

No hay criterio 23 (el ultimo que agregé). Aunque bien y puede ser que esta paginación sea solo de departamentos pero igual lo comento

2024-06-14 17:49 UTC, samurojasp requested changes
![image](https://github.com/samurojasp/GreeniePanelAdmin/assets/75285856/3946119b-8e4c-4e11-b60a-4041bcad15a1)
Después de el índice 8 cree del 9 al 11 y supongo se debería mostrar en la siguiente página pero no puedo pasar a la siguiente xd

2024-06-15 00:29 UTC, GreenieWarren commented
Ahora si furula bro

2024-06-15 00:30 UTC, merged