Feature/toast
samurojasp/GreeniePanelAdmin pull request #14
Opened 2024-06-18 20:45 UTC by Charbelsaad21

2024-06-19 10:55 UTC, Hector1567XD commented
Grande Charbel

2024-06-19 10:55 UTC, Hector1567XD commented on src/app/app.routes.ts
> -      },
Seria bueno tener una ruta de 404 btw

2024-06-19 10:56 UTC, Hector1567XD commented on src/app/views/indicators/list-indicators/indicators.component.ts
> +        this.toggleToast('Error al eliminar el indicador', false);
Seria bueno mostrar los errores que vienen del backend en lugar de quemar un mensaje generico, asi pueden venir las validaciones y mas detalles desde alla

2024-06-20 01:16 UTC, Hector1567XD requested changes
Bueno, esto dejo de ser opcional

2024-06-20 01:16 UTC, Hector1567XD commented on src/app/views/criteria/create/create.component.ts
> +          this.toggleToast('Error al crear criterio', false);
```suggestion
          this.toggleToast(error.message, false); 
```
o....
```suggestion
          this.toggleToast(error.error.message, false); 
```
Como sea que lo envie el backend

2024-06-20 03:09 UTC, samurojasp commented on src/app/app.routes.ts
> -      },
Si la hay, eso es que estaba repetida

2024-06-22 00:03 UTC, GreenieWarren requested changes
exitos hermanao

2024-06-22 00:03 UTC, GreenieWarren commented on src/app/views/departments/edit/edit.component.ts
> +          this.toggleToast('Error al editar usuario', false);
Creo que aquí debería decir que se edito exitosa o erronamente un departamento, no un usuario

2024-06-22 00:03 UTC, GreenieWarren commented on src/app/views/indicators/edit-indicator/edit-indicator.component.ts
> +      this.toggleToast('Usuario editado exitosamente', true);
Y aquí ocurre lo mismo también. Debería de ser indicador editado erronea/correcta mente

2024-06-26 04:48 UTC, samurojasp commented
Prueben otra vez que ya arreglé

2024-06-26 04:48 UTC, samurojasp approved these changes

2024-06-29 17:05 UTC, GreenieWarren approved these changes
Adelante hermanao, hora del merge

2024-06-30 06:40 UTC, merged